{% set version = "1.9.8rc2" %}

package:
  name: cdo
  version: {{ version }}

source:
  url: https://code.mpimet.mpg.de/attachments/download/20539/cdo-{{ version }}.tar.gz
  sha256: f8a00e6cd89cabbd5da31aab05d29cb7f3bd5cd912ffb62093b20008c6fcfb90

build:
  number: 0
  skip: True  # [win]
  script_env:
    - LIBS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - jasper
    - libnetcdf
    - proj4
    - eccodes
    - udunits2
    - libxml2
    - fftw
    - cmor
    - json-c
    - libuuid
  run:
    - jasper
    - libnetcdf
    - proj4
    - eccodes
    - udunits2
    - libxml2
    - fftw
    - cmor
    - libuuid

test:
  files:
    - dummy.nc
  commands:
    - cdo -h
    - cdo sinfo dummy.nc

about:
  home: https://code.zmaw.de/projects/cdo
  license: GPL-2.0

  license_file: COPYING
  summary: 'CLI tools to manipulate and analyse Climate and NWP model Data'

extra:
  recipe-maintainers:
    - Try2Code
    - ocefpaf
