{% set version = "1.9.5rc1" %}

package:
  name: cdo
  version: {{ version }}

source:
  url: https://code.zmaw.de/attachments/download/17451/cdo-{{ version }}.tar.gz
  sha256: 906e03f5518488726f8447c6ff4f7fa8
build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - jasper
    - libnetcdf 4.4.*
    - proj4 4.9.3
    - util-linux  # [linux]
    - eccodes
    - udunits2
    - libxml2 2.9.*
    - fftw
    - cmor
    - json-c 0.12.1
    - ossuuid 1.6.2 0
  run:
    - jasper
    - libnetcdf 4.4*
    - proj4 4.9.3
    - libgcc  # [linux]
    - util-linux  # [linux]
    - eccodes
    - udunits2
    - libxml2 2.9.*
    - fftw
    - cmor
    - ossuuid 1.6.2 0

test:
  files:
    - dummy.nc
  commands:
    - cdo -h
    - cdo sinfo dummy.nc  # [linux]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://code.zmaw.de/projects/cdo
  license: GPL-2.0
  summary: 'CLI tools to manipulate and analyse Climate and NWP model Data.'

extra:
  recipe-maintainers:
    - ocefpaf
