{% set version = "2.0.0rc1" %}

package:
  name: cdo
  version: {{ version }}

source:
  url: https://code.mpimet.mpg.de/attachments/download/22243/cdo-{{ version }}.tar.gz
  sha256: acd9a6515afe03fe7950adf9a17acd253e3b4d2004f9206ff55da6c7b0f937a5

build:
  number: 0
  skip: True  # [win]
  script_env:
    - LIBS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - llvm-openmp  # [osx]
  host:
    - llvm-openmp  # [osx]
    - jasper
    - libnetcdf
    - proj
    - eccodes
    - udunits2
    - libxml2
    - fftw
    - cmor
    - json-c
    - libuuid
  run:
    - jasper
    - libnetcdf
    - proj
    - eccodes
    - udunits2
    - libxml2
    - fftw
    - cmor
    - libuuid

test:
  files:
    - dummy.nc
  commands:
    - cdo -h
    - cdo sinfo dummy.nc

about:
  home: https://code.zmaw.de/projects/cdo
  license: GPL-2.0

  license_file: COPYING
  summary: 'CLI tools to manipulate and analyse Climate and NWP model Data'

extra:
  recipe-maintainers:
    - Try2Code
    - ocefpaf
