{% set version = "1.9.8rc1" %}

package:
  name: cdo
  version: {{ version }}

source:
  url: https://code.mpimet.mpg.de/attachments/download/20539/cdo-{{ version }}.tar.gz
  sha256: e401e67a2853cf9cc9b0cd611c2d6ef05e16c16dca272e34871f776f0fa5913a

build:
  number: 0
  skip: True  # [win]
  script_env:
    - LIBS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - jasper
    - libnetcdf
    - proj4
    - eccodes
    - udunits2
    - libxml2
    - fftw
    - cmor
    - json-c
    - libuuid
  run:
    - jasper
    - libnetcdf
    - proj4
    - eccodes
    - udunits2
    - libxml2
    - fftw
    - cmor
    - libuuid

test:
  files:
    - dummy.nc
  commands:
    - cdo -h
    - cdo sinfo dummy.nc

about:
  home: https://code.zmaw.de/projects/cdo
  license: GPL-2.0

  license_file: COPYING
  summary: 'CLI tools to manipulate and analyse Climate and NWP model Data'

extra:
  recipe-maintainers:
    - Try2Code
    - ocefpaf
