{% set version = "1.9.3" %}

package:
  name: cdo
  version: {{ version }}

source:
  url: https://code.zmaw.de/attachments/download/16435/cdo-{{ version }}.tar.gz
  sha256: e83a3de7b402600c0d9a5df18073d36d133ff9719d3c561a0efa90f9c1599f3f

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - jasper
    - libnetcdf 4.5.*
    - proj4 4.9.3
    - util-linux  # [linux]
    - eccodes
    - udunits2
    - libxml2 2.9.*
    - fftw
    - cmor 3.3.0
    - json-c 0.12.1
    - ossuuid 1.6.2 0
  run:
    - jasper
    - libnetcdf >=4.5
    - proj4 4.9.3
    - libgcc  # [linux]
    - util-linux  # [linux]
    - eccodes
    - udunits2
    - libxml2 2.9.*
    - fftw
    - cmor 3.3.0
    - ossuuid 1.6.2 0

test:
  files:
    - dummy.nc
  commands:
    - cdo -h
    - cdo sinfo dummy.nc  # [linux]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://code.zmaw.de/projects/cdo
  license: GPL-2.0
  summary: 'CLI tools to manipulate and analyse Climate and NWP model Data.'

extra:
  recipe-maintainers:
    - ocefpaf
