{% set version = "1.9.4" %}

package:
  name: cdo
  version: {{ version }}

source:
  url: https://code.mpimet.mpg.de/attachments/download/17438/cdo-{{ version }}-fix.tar.gz
  sha256: 1727f20dcc11c57195689e7d99b9b7968037f8b3afe5b9c7a6cf7997cf7bb95a

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - jasper
    - libnetcdf
    - proj4
    - util-linux  # [linux]
    - eccodes
    - udunits2
    - libxml2
    - fftw
    - cmor
    - json-c 0.12.1
    - ossuuid 1.6.2 0
  run:
    - jasper
    - libnetcdf
    - proj4
    - util-linux  # [linux]
    - eccodes
    - udunits2
    - libxml2
    - fftw
    - cmor
    - ossuuid 1.6.2 0

test:
  files:
    - dummy.nc
  commands:
    - cdo -h
    - cdo sinfo dummy.nc  # [linux]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://code.zmaw.de/projects/cdo
  license: GPL-2.0
  summary: 'CLI tools to manipulate and analyse Climate and NWP model Data.'

extra:
  recipe-maintainers:
    - Try2Code
    - ocefpaf
