travis:
  secure:
    BINSTAR_TOKEN: PEE5pp2iyGgAPCZTjwZ4284pvgcQbvYKjAqiVXemmQ8fgH81TDp8nK3YxLDMfrrdykpwictBmTBO/BK5Tf6MbbQHnvdXVbEXUgWEXOH7ARNwuaEbXvtg++QhvlRqqpFDc0fEDpF9x7Og9RMoFOalY4/XkRjD31nbQil1GxDvqTJwW7wmxLu5iVo/X/H0tmayL2EktFwJAdnp3YNKlNx2iV31gtOg8vUVeaWvc1onYhxn8uInpRIk7AbQELQK9weIdJfSGyewaaSwEv/Vnrjg2hl0lfUoaGSSwtcx3OIz1ickxVJ4uegnbwHIXWIIT1e9qWeQUKD1i2lMwdHl8uLKBSvXhZKrZI5fxNcLaNZhBWJlQBtihoSHwjWsRjTea9b009VfYmUGyVeCML/jd5sl+yWTEtq8U9Bt9TSPzwVtKilS/63+2f7EDJEmfKJCMZJYL6S++L8fYP6SPQyQiLfGmZeLJV18oFt6CU5S3IlnUN8szEHoBhP8escYEd2CngYJiwyEZ8cK795UX0BOQAqVK/V1DLWJBEyBjdmO06Ifo9nYHvmdkOgWDTNWHiGNNyPKVlq9uAp/fEiYYHhTp4UYksB1CtqFL33oOq8AgLomt0YPkEa1UpaoSgNKbumjtVxXkmRTlCJOh4q/pJO4MsqO+RokaT983/vkVkcWlYYeJoY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
provider:
  osx: circle